"""initial schema

Revision ID: 9ebc57cb4f08
Revises:
Create Date: 2026-07-18 18:50:54.034187
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ebc57cb4f08"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("avatar", sa.String(length=512), nullable=True),
        sa.Column("bio", sa.String(length=280), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_activity_logs_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_activity_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("folder", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chats_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chats_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_group", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_id"), ["id"], unique=False)

    op.create_table(
        "dead_drops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("encrypted_payload", sa.Text(), nullable=True),
        sa.Column("stego_filename", sa.String(length=255), nullable=True),
        sa.Column("preview", sa.String(length=140), nullable=True),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("burn_after_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dead_drops", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dead_drops_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_dead_drops_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dead_drops_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dead_drops_token"), ["token"], unique=True)

    op.create_table(
        "one_time_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("one_time_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_one_time_tokens_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_one_time_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_one_time_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.Column("accent", sa.String(length=16), nullable=False),
        sa.Column("animations_enabled", sa.Boolean(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("auto_delete_messages", sa.Boolean(), nullable=False),
        sa.Column("default_encryption", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_settings_user_id"), ["user_id"], unique=True)

    op.create_table(
        "share_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=48), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("stego_filename", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("access_password_hash", sa.String(length=255), nullable=True),
        sa.Column("max_reads", sa.Integer(), nullable=True),
        sa.Column("read_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("share_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_share_tokens_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_share_tokens_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_share_tokens_token"), ["token"], unique=True)

    op.create_table(
        "conversation_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("last_read_id", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "user_id", name="uq_conversation_member"),
    )
    with op.batch_alter_table("conversation_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_members_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversation_members_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversation_members_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "direct_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("stego_filename", sa.String(length=255), nullable=True),
        sa.Column("has_decoy", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("direct_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_direct_messages_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_direct_messages_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_direct_messages_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_direct_messages_sender_id"), ["sender_id"], unique=False
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("encrypted_message", sa.Text(), nullable=True),
        sa.Column("preview", sa.String(length=140), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("stego_filename", sa.String(length=255), nullable=True),
        sa.Column("has_decoy", sa.Boolean(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_chat_id"), ["chat_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_id"))
        batch_op.drop_index(batch_op.f("ix_messages_chat_id"))

    op.drop_table("messages")
    with op.batch_alter_table("direct_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_direct_messages_sender_id"))
        batch_op.drop_index(batch_op.f("ix_direct_messages_id"))
        batch_op.drop_index(batch_op.f("ix_direct_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_direct_messages_conversation_id"))

    op.drop_table("direct_messages")
    with op.batch_alter_table("conversation_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_members_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_members_conversation_id"))

    op.drop_table("conversation_members")
    with op.batch_alter_table("share_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_share_tokens_token"))
        batch_op.drop_index(batch_op.f("ix_share_tokens_owner_id"))
        batch_op.drop_index(batch_op.f("ix_share_tokens_id"))

    op.drop_table("share_tokens")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_user_id"))
        batch_op.drop_index(batch_op.f("ix_settings_id"))

    op.drop_table("settings")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("one_time_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_one_time_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_one_time_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_one_time_tokens_id"))

    op.drop_table("one_time_tokens")
    with op.batch_alter_table("dead_drops", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dead_drops_token"))
        batch_op.drop_index(batch_op.f("ix_dead_drops_owner_id"))
        batch_op.drop_index(batch_op.f("ix_dead_drops_id"))
        batch_op.drop_index(batch_op.f("ix_dead_drops_expires_at"))

    op.drop_table("dead_drops")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("chats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chats_owner_id"))
        batch_op.drop_index(batch_op.f("ix_chats_id"))

    op.drop_table("chats")
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_activity_logs_id"))
        batch_op.drop_index(batch_op.f("ix_activity_logs_created_at"))

    op.drop_table("activity_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
