"""add totp 2fa columns to users

Revision ID: ef702b77cf9b
Revises: 9ebc57cb4f08
Create Date: 2026-07-18 14:16:56.978140
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef702b77cf9b"
down_revision: str | None = "9ebc57cb4f08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("totp_secret", sa.String(length=64), nullable=True))
        # server_default so the NOT NULL column can be added to a table that
        # already has rows; existing users default to 2FA disabled.
        batch_op.add_column(
            sa.Column(
                "totp_enabled",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(sa.Column("totp_recovery_codes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("totp_recovery_codes")
        batch_op.drop_column("totp_enabled")
        batch_op.drop_column("totp_secret")

    # ### end Alembic commands ###
